name: 'Okteto Test'
description: 'Run tests in Okteto manifest'
inputs:
  name:
    description: "The name of the dev environment"
    required: false
    default: ""
  namespace:
    description: "The namespace scope for this action. Defaults to the current context if not specified."
    required: false
    default: ""
  file:
    description: "Path to the Okteto manifest file. Defaults to the default path if not specified."
    required: false
    default: ""
  deploy:
    description: 'Deploy the dev environment even if it has already been deployed'
    required: false
    default: 'false' 
  no-cache:
    description: 'Do not use the cache when running the tests'
    required: false
    default: 'false'
  variables:
    description: "Variables to be used by the dev environment. If multiple variables are present, separate them with commas (e.g., VAR1=VAL1,VAR2=VAL2)"
    required: false
    default: ""
  timeout:
    description: "The length of time to wait for completion (e.g., 1s, 2m, 3h)"
    required: false
    default: "5m"
  tests:
    description: "The test sections to run, separated by spaces. Runs all tests if no tests are defined (e.g., 'unit integration')."
    required: false
    default: ""
  log-level:
    description: "Log level for the action. Valid options: debug, info, warn, error."
    required: false
    default: "" 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.file }}
    - ${{ inputs.deploy }}
    - ${{ inputs.no-cache }}
    - ${{ inputs.variables }}
    - ${{ inputs.timeout }}
    - ${{ inputs.tests }}
    - ${{ inputs.log-level }}

branding:
  color: 'green'
  icon: 'layers'
